CREATE TABLE "Customers" (
  "customer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "customer_name" varchar,
  "segment" varchar
);

CREATE TABLE "Products" (
  "product_id" varchar PRIMARY KEY,
  "product_name" varchar,
  "category" varchar,
  "sub_category" varchar
);

CREATE TABLE "Locations" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "country" varchar,
  "state" varchar,
  "market" varchar,
  "region" varchar
);

CREATE TABLE "Orders" (
  "order_id" varchar PRIMARY KEY,
  "order_date" date,
  "ship_date" date,
  "ship_mode" varchar,
  "order_priority" varchar,
  "year" int,
  "customer_id" int NOT NULL,
  "location_id" int NOT NULL
);

CREATE TABLE "OrderItems" (
  "order_item_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" varchar NOT NULL,
  "product_id" varchar NOT NULL,
  "quantity" int,
  "sales" decimal(10,2),
  "discount" decimal(5,2),
  "profit" decimal(10,2),
  "shipping_cost" decimal(10,2)
);

ALTER TABLE "Orders" ADD FOREIGN KEY ("customer_id") REFERENCES "Customers" ("customer_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "Orders" ADD FOREIGN KEY ("location_id") REFERENCES "Locations" ("location_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("order_id") REFERENCES "Orders" ("order_id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "OrderItems" ADD FOREIGN KEY ("product_id") REFERENCES "Products" ("product_id") DEFERRABLE INITIALLY IMMEDIATE;
